FROM ubuntu:18.04
RUN apt update; apt install -y gnupg2; apt install -y python3-pip
WORKDIR /dir
COPY requirements.txt requirements.txt
COPY run.py run.py
COPY app/ app
RUN pip3 install -r requirements.txt
ENTRYPOINT python3 run.py